spring.application.name=ContentGeneratorAgent
external.write.service.url=${SERVER_URL:http://localhost:8000}
spring.webflux.buffer-size=1
spring.codec.max-in-memory-size=33554432
spring.datasource.url= jdbc:postgresql://db.bcndglammmumaxqcwhqr.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=lm6RTs5w5RMa6Lgf
spring.jpa.hibernate.ddl-auto=update
# Enable reactive logging
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty=DEBUG