spring.application.name=ContentGeneratorAgent
external.write.service.url=${SERVER_URL:http://localhost:8000}
spring.webflux.buffer-size=1
spring.codec.max-in-memory-size=33554432

# Enable reactive logging
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty=DEBUG