spring.application.name=ContentGeneratorAgent
external.write.service.url=${SERVER_URL:http://localhost:8000}
spring.webflux.buffer-size=1
spring.codec.max-in-memory-size=33554432
spring.datasource.url=jdbc:postgresql://db.npzqqeuoisnsgmarqnas.supabase.co:5432/postgres?user=postgres
spring.datasource.username=postgres.npzqqeuoisnsgmarqnas
spring.datasource.password=oSZCWuABtNEnKSuz
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Enable reactive logging
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty=DEBUG
server.port=${PORT:8080}
